aliases:
    fleeks: cd ~/.local/share/fleek
bling: default
blocklist: []
byo_git: false
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: true
    autopull: true
    autopush: true
    enabled: true
min_version: 0.8.4
name: Fleek Configuration
overlays: {}
packages:
    - helix
paths:
    - $HOME/bin
    - $HOME/.local/bin
programs:
    - dircolors
shell: zsh
systems:
    - arch: aarch64
      hostname: trillian
      os: darwin
      username: mjh
track: nixos-unstable
unfree: true
users:
    - email: 22219356+matthew-hollick@users.noreply.github.com
      name: Matthew Hollick
      ssh_private_key_file: ~/.ssh/id_hmrc_github
      ssh_public_key_file: ~/.ssh/id_hmrc_github.pub
      username: mjh
