aliases:
    cdsrc: cd ~/src/HMRC
    fleeks: cd /Users/mjh/.local/share/fleek
    gitsub: git submodule update --init --recursive
    ls: exa
    awssso: op item get 'Amazon - HMRC' --otp | assume-role
bling: none
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: true
    autopull: true
    autopush: true
    enabled: true
min_version: ""
name: Fleek Configuration
overlays: {}
packages:
    - helix
    - sbt
    - aws-assume-role
    - awslogs
    - awsls
    - steampipe
    - python3
    - go
    - silver-searcher
    - atuin
    - tfswitch
    - virtualenv
    - micromamba
    - pew
    - tgswitch
    - kubecolor
    - kubectl
    - kubectl-tree
    - krew
    - kubectl-gadget
    - kubectl-evict-pod
    - clusterctl
    - talosctl
    - nmap
    - pre-commit
    - docker
    - docker-compose
    - xquartz
    - podman
    - podman-compose
    - podman-tui
    - bat
    - present
    - get_iplayer
    - ffmpeg_6
    - R
    - bash-my-aws
    - awstats
    - aws-rotate-key
    - awscli2
    - gh
    - tfsec
    - nmap-formatter
    - nmap-unfree
    - stdenv
    - jq
    - terraform-docs
paths:
    - $HOME/bin
    - $HOME/.local/bin
    - $HOME/bin
    - /opt/homebrew/bin
    - /opt/homebrew/sbin
programs:
    - dircolors
    - exa
    - zoxide
    - direnv
    - neovim
shell: zsh
systems:
    - arch: aarch64
      hostname: trillian
      os: darwin
      username: mjh
unfree: true
users: []
