aliases:
    cat: bat
    fleeks: cd /Users/mjh/.local/share/fleek
    gitsub: git submodule update --init --recursive
    ls: exa
bling: low
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: true
    autopull: true
    autopush: true
    enabled: true
name: Fleek Configuration
packages:
    - helix
    - sbt
    - aws-assume-role
    - awscli
    - awslogs
    - awsls
    - steampipe
    - python3
    - go
    - silver-searcher
    - atuin
    - tfswitch
    - virtualenv
    - micromamba
    - pew
    - tgswitch
    - kubecolor
    - kubectl
    - kubectl-tree
    - krew
    - kubectl-gadget
    - kubectl-evict-pod
    - clusterctl
    - talosctl
    - nmap
    - pre-commit
    - docker
    - docker-compose
    - xquartz
    - podman
    - podman-compose
    - podman-tui
    - podman-desktop
paths:
    - $HOME/bin
    - $HOME/.local/bin
    - $HOME/bin
    - /opt/homebrew/bin
    - /opt/homebrew/sbin
programs:
    - dircolors
    - exa
    - bat
    - zoxide
    - direnv
    - neovim
shell: zsh
systems:
    - arch: aarch64
      hostname: trillian
      os: darwin
      username: mjh
unfree: true
