aliases:
    cdsrc: cd ~/src/HMRC
    fleeks: cd /Users/mjh/.local/share/fleek
    gitsub: git submodule update --init --recursive
    ls: exa
bling: none
blocklist: []
byo_git: false
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: true
    autopull: true
    autopush: true
    enabled: true
min_version: ""
name: Fleek Configuration
overlays: {}
packages:
    - helix
    - sbt
    - aws-assume-role
    - awslogs
    - awsls
    - steampipe
    - python3
    - go
    - silver-searcher
    - atuin
    - tfswitch
    - virtualenv
    - micromamba
    - pew
    - tgswitch
    - kubecolor
    - kubectl
    - kubectl-tree
    - krew
    - kubectl-gadget
    - kubectl-evict-pod
    - clusterctl
    - talosctl
    - nmap
    - pre-commit
    - docker
    - docker-compose
    - xquartz
    - podman
    - podman-compose
    - podman-tui
    - bat
    - present
    - ffmpeg_6
    - R
    - bash-my-aws
    - awstats
    - aws-rotate-key
    - awscli2
    - gh
    - tfsec
    - nmap-formatter
    - nmap-unfree
    - stdenv
    - jq
    - terraform-docs
    - powerline-fonts
    - darkhttpd
    - kafkactl
    - kafkacat
    - graphviz
    - curl
    - rsync
    - btop
    - raycast
    - socat
    - netcat
    - go-task
    - pipx
    - obsidian
    - ctop
    - tldr
    - iterm2
    - maven
    - jmeter
    - expect
    - kind
    - nikto
    - aws-mfa
    - mr
    - pwgen
paths:
    - $HOME/bin
    - $HOME/.local/bin
    - /opt/homebrew/bin
    - /opt/homebrew/sbin
    - $HOME/Library/Python/3.9/bin
programs:
    - dircolors
    - exa
    - zoxide
    - direnv
    - neovim
shell: zsh
systems:
    - arch: aarch64
      hostname: trillian
      os: darwin
      username: mjh
track: ""
unfree: true
users:
    - email: 22219356+matthew-hollick@users.noreply.github.com
      name: Matthew Hollick
      ssh_private_key_file: ~/.ssh/hedgehog
      ssh_public_key_file: ~/.ssh/hedgehog.pub
      username: mjh
