aliases:
    fleeks: cd ~/.local/share/fleek
    otp: op item get 'Amazon - HMRC' --otp
allow_broken: false
auto_gc: false
bling: none
blocklist:
    - mesa
byo_git: true
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: false
    autopull: false
    autopush: false
    enabled: false
min_version: 0.8.4
name: Fleek Configuration
overlays: {}
packages:
    - helix
    - sbt
    - aws-assume-role
    - awslogs
    - awsls
    - python3
    - go
    - silver-searcher
    - atuin
    - tfswitch
    - virtualenv
    - micromamba
    - pew
    - tgswitch
    - kubecolor
    - kubectl-tree
    - krew
    - kubectl-gadget
    - kubectl-evict-pod
    - clusterctl
    - nmap
    - pre-commit
    - docker
    - docker-compose
    - podman
    - podman-compose
    - podman-tui
    - bat
    - present
    - ffmpeg_6
    - R
    - bash-my-aws
    - awstats
    - aws-rotate-key
    - awscli2
    - gh
    - tfsec
    - nmap-formatter
    - nmap-unfree
    - stdenv
    - jq
    - terraform-docs
    - powerline-fonts
    - darkhttpd
    - kafkactl
    - kafkacat
    - graphviz
    - curl
    - rsync
    - btop
    - socat
    - netcat
    - go-task
    - pipx
    - obsidian
    - ctop
    - tldr
    - iterm2
    - maven
    - jmeter
    - expect
    - kind
    - nikto
    - aws-mfa
    - mr
    - pwgen
    - cachix
    - discord
    - pandoc
    - asciidoctorj
    - vscode
    - rename
    - icdiff
    - lftp
    - hugo
    - nodejs
    - htop
    - tflint
    - mtr
    - lima
    - gnused
    - gawk
    - jsawk
    - gnuplot
    - jpegoptim
    - jpegrescan
    - tree
    - jdk
    - python310Packages.jupyter
    - imagemagick
    - wget
    - python310Packages.tkinter
    - packer
    - pdftk
    - texlive.combined.scheme-medium
    - oh-my-zsh
    - _1password-gui
    - _1password
    - units
    - aws-vault
    - zoom-us
    - clickhouse
    - pngcrush
    - steampipe
    - po4a
    - bb
    - colima
    - fx
    - visualvm
    - copilot-cli
    - lzma
    - commonsCompress
    - httpie
    - lynx
    - clamav
    - xz
    - pixz
    - automake
    - autoconf
paths:
    - $HOME/bin
    - $HOME/.local/bin
programs:
    - dircolors
    - eza
    - zoxide
    - direnv
    - neovim
shell: zsh
systems:
    - arch: aarch64
      home: ""
      hostname: trillian
      os: darwin
      user:
        email: 22219356+matthew-hollick@users.noreply.github.com
        name: Matthew Hollick
        ssh_private_key_file: ~/.ssh/id_hmrc_github
        ssh_public_key_file: ~/.ssh/id_hmrc_github.pub
        username: mjh
      username: mjh
track: nixos-unstable
unfree: true
users:
    - email: 22219356+matthew-hollick@users.noreply.github.com
      name: Matthew Hollick
      ssh_private_key_file: ~/.ssh/id_hmrc_github
      ssh_public_key_file: ~/.ssh/id_hmrc_github.pub
      username: mjh
